### PR TITLE
35 modifyfix scintillation time function

### LINKED ISSUE #35: modify/fix scintillation time function
The current implementation (inherited from kloe) produces late photo-electrons for high-energy deposits from electrons. In particular for energy deposit in SAND, the distribution of the photo-electron scintillation time has entries after the acquisition time + dead time, resulting in two consecutive signals.
The solution is to use an exponential distribution for the scintillation time.

### PR DESCRIPTION
**Pull request by mt82**
1. I added `rise_time` and `decay_time` in `utils.h`
2. I added a function `photons_emission_time` to get the photon emission time as in [geant4](https://github.com/Geant4/geant4/blob/e58e650b32b961c8093f3dd6a2c3bc917b2552be/source/processes/electromagnetic/xrays/src/G4Scintillation.cc#L638)

### CODE REVIEW

**Comment by denisecasazza** [comment]
In line https://github.com/DUNE/sandreco/blob/8de87835c17d486f38a02a11847c947c7cd17b6f/src/SANDDigitization.cpp#L26 exponential has to be replaced with log function as follows : `t  = -1.0 * sand_reco::ecal::scintillation::decay_time * TMath::Log(1.0 - rand.Uniform() );`

**Comment by pgauzzi** [comment]
OK, the two curves are similar in the first part, from 0 to 10 ns, and this one has a less pronounced tail at long times.
I also checked the Fortran code of the KLOE Monte Carlo, and indeed there is a cut at 50 ns.
If we keep also the function  photons_emission_time_as_kloe() I suggest to add this cut.

**Comment by mt82** [comment]
I reopened the pull request since there was a bug. `TMath::Log` shpuld be used instead of `TMath::Exp`

**Comment by mt82** [comment]
Implement the new scintillation time after the fix

**Review by pgauzzi — APPROVED** [review]

**Pull request merged**
